#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把验证码转成 ASCII art，人工确认算式"""
from PIL import Image

for i in range(3):
    img = Image.open('/tmp/vcode_%d.jpg' % i).convert('L')
    # 放大4x便于观察
    img = img.resize((img.width * 4, img.height * 4), Image.LANCZOS)
    w, h = img.size
    print('==== img%d (%dx%d) ====' % (i, w, h))
    # 阈值二值化：深色=字符
    chars = ' .:-=+*#%@'
    for y in range(h):
        row = ''
        for x in range(w):
            p = img.getpixel((x, y))
            idx = min(len(chars) - 1, (255 - p) * len(chars) // 256)
            row += chars[idx]
        print(row)