#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""验证码干净版 ASCII（放大2x，阈值>>字符），判断干扰线"""
from PIL import Image
import glob, re

for p in sorted(glob.glob('/tmp/vcodes/*.jpg'))[:6]:
    img = Image.open(p).convert('L')
    img = img.resize((img.width * 2, img.height * 2), Image.LANCZOS)
    w, h = img.size
    print('==== %s ====' % p.split('/')[-1])
    for y in range(h):
        row = ''
        for x in range(w):
            row += '#' if img.getpixel((x, y)) < 110 else '.'
        print(row)